version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql
    container_name: postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=patient-service-db
    volumes:
      - postgresql_data:/bitnami/postgresql
    ports:
      - "5432:5432"
    networks:
      - patient-app-nw

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - patient-app-nw

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_CLUSTER_ID=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - patient-app-nw

volumes:
  postgresql_data:
  pgadmin_data:
  kafka_data:

networks:
  patient-app-nw:
    external: true
