server:
  port: 4004

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/patient-management-realm
          jwk-set-uri: http://keycloak:8080/realms/patient-management-realm/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-routes
              uri: http://patient-service-container:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-routes
              uri: http://patient-service-container:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - name: RewritePath
                  args:
                    regexp: /api-docs/patients
                    replacement: /v3/api-docs